### ISSUE TITLE
Tâches à faire

### ISSUE THREAD

**Issue by detobel36** [RobinPetit/OpenWifiLocalizator#1]
## Application pour enregistrer les points
Il faut commencer par faire une application permettant d'enregistrer des points.  Lors de l'enregistrement d'un point on enregistre la liste des wifi en relation avec sa position sur la carte.             
Concrètement:
- Afficher une carte (possibilité de zoom)
- Positionner un pointeur sur la carte
- Enregistrer les points en XML (on doit enregistrer: la positions sur la carte, les wifi et leur intensité)

## Application utilisateur
L'application doit pouvoir afficher la carte, localiser l'utilisateur dessus et le guider.         
Il faut donc afficher une carte où on localise l'utilisateur.  Il a l'occasion de rentrer un local/bâtiment et d'être guidé jusqu’à celui-ci.

**Comment by NathanLiccardo** [comment]
Au niveau des cartes on devrait recevoir tout d'ici lundi :) 

Bonjour,
 
Les plans sont sur le serveur informatique du département des Infrastructures, contenant des informations « confidentielles ». Je vais rassembler tout ça et vous faire un (ou plusieurs) wetransfer. Je vous transmettrai l’ensemble des plans lundi prochain, courant de journée.
 
Bon après-midi et bon week-end.
 
Bruno Delcroix
 
T : +32 (0)2 650 35 02
G : +32 (0)492 84 91 44
F : +32 (0)2 650 41 96
UniversitÃ© libre de Bruxelles

Département des Infrastructures
Service "Projets & Constructions"
Courrier : Av. F. Roosevelt 50, CP 112, 1050 Bruxelles
Visiteurs : Av. A. Buyl 121, 1er étage, 1050 Bruxelles
www.ulb.be/dinfra

**Comment by RobinPetit** [comment]
Bon ça c'est déjà une bonne nouvelle ! Par rapport au graphe, comment va-t-on le créer ? Au niveau des nœuds, ça va pas être trop compliqué, mais il va falloir faire les liens. Du coup comment va-t-on attaquer le problème ?
On stocke les différents bâtiments (étages) dans des fichiers séparés ? Je propose qu'on se fasse un script Python ou autre qui gère une mini interface graphique avec laquelle on peut faire les sous-graphes non-connexes de chaque étage et qui enregistre dans un format spécifique facilement lisible et éditable par exemple. Et une fois que tout ça est fait, on regroupe tout dans un seul fichier représentant le graphe et que l'on peut utiliser dans notre application.

Vous en pensez quoi ?

**Comment by denishoornaert** [comment]
Je pense que stocker chaque batiment dans un fichier séparé est une bonne idée mais avoir un fichier pour chaque étage sera p-e un peu too mush. Il faudra aussi alors considérer avoir un fichier pour l'extérieur.
Pour ce qui est du script, c'est une bonne idée. Perso les deux seul lib pour GUI que je maitrise assez bien sont Qt5 et gtkmm (en c++ donc) mais j'ai pas de soucis a en apprendre une autre ;)

**Comment by RobinPetit** [comment]
Le souci si on traite ça en C++, c'est qu'on risque d'un peu se prendre la tête en dev alors que ça peut se scripter facilement en Python avec Tkinter par exemple. Et en plus, on a vite des problèmes de compatibilité avec les libs C++. InstllerQt, c'est pénible, ça prend de la place, etc.
Je pense qu'il est préférable de faire un tout petit script facile qui se débug facilement, et qui installe tkinter avec `sudo apt-get install python3-tkinter` si ce n'est pas déjà fait. Nan ?

**Comment by denishoornaert** [comment]
Pas de soucis pour ma part ;)

**Comment by RobinPetit** [comment]
J'ouvre une nouvelle issue pour discuter des besoins de cette appli.

**Comment by RobinPetit** [comment]
Du coup, ici c'est fini, pour la suite des choses à faire, voir #7.
