### ISSUE TITLE
Nettoyage

### ISSUE THREAD

**Issue by detobel36** [RobinPetit/OpenWifiLocalizator#13]
Je propose qu'on voie un peu ce qui doit être supprimé/modifié/... pour mettre un peu d'ordre :stuck_out_tongue:                  

- [x] [Branche Prototype] :x: supprimer le dossier `prototype` (je veux juste être sur que tout le monde ai fait un backup des modifications qu'il aurait faite)
- [x] :question: faut-il garder la branche `XMLMerger` ?
- [x] :question: faut-il supprimer le branche `Gui` (vu qu'elle a fusionnée avec prototype) ?
- [x] [Branche Prototype] :question: faut-il supprimer les dossiers `.idea` (vu qu'on est tous sur AndroidStudio c'est cool pour pas devoir config mais si ça change dès qu'on commit c'est pas cool :confused: )

**Comment by RobinPetit** [comment]
Pour Gui, si la branche a été mergée et qu'il n'y a rien de nouveau dessus, on vire.

Pour XMLMerger, on peut fermer je pense.

**Comment by detobel36** [comment]
Je pense qu'on va garder `.idea`              
Je ne sais pas trop ce que ça fait mais vu qu'on est tous sur AndroidStudio et que le fichier ne contient pas de chemin absolue je pense que ça va aller :smiley:           
Je pense également qu'on peut supprimer `XMLMerger` (comme c'est pas moi qui ai bossé dessus je veux être sur de pas supprimer du boulot :stuck_out_tongue: )

**Comment by RobinPetit** [comment]
Allez-y pour XMLMerger. ;)

**Comment by RobinPetit** [comment]
Il sert à quoi ce dossier `.idea/` ?

**Comment by detobel36** [comment]
La est toute la question :stuck_out_tongue:

**Comment by RobinPetit** [comment]
Oh...

**Comment by denishoornaert** [comment]
C'est un fichier de gestion de projet généré par intelij. Bref mieux vaut pas le supprimer :p

**Comment by RobinPetit** [comment]
Ok. Donc on ne supprime pas, on on ferme l'issue ? :cactus:

**Comment by denishoornaert** [comment]
Non conservons la au cas ou on aurait encore ce genre d' "issue" ;)

**Comment by RobinPetit** [comment]
On peut fermer puis réouvrir. ;)
