### ISSUE TITLE
Mettre à jour l'UML

### ISSUE THREAD

**Issue by detobel36** [RobinPetit/OpenWifiLocalizator#14]
L'UML n'est pas à jour...  Il faudra qu'on ai qqch de claire pour montrer le jour J :stuck_out_tongue:

**Comment by RobinPetit** [comment]
Oulilè l'UML ?

**Comment by detobel36** [comment]
`rapport/UML`

**Comment by RobinPetit** [comment]
Makes sense...

**Comment by denishoornaert** [comment]
Je peux le mettre à jour si vous le voulez :p J'ai plein de temps :p

**Comment by denishoornaert** [comment]
>voila c'est fait. C'est ajour avec ce qui est présent actuellement sur la branch prototype ;)

**Comment by RobinPetit** [comment]
Du coup je suppose que l'on va devoir rechanger l'UML pour cette release ?

**Comment by denishoornaert** [comment]
Du coup on en fait un pour l'interface android ou balek ? Si non, on peut alors fermer cette issue je pense.

**Comment by RobinPetit** [comment]
Du coup, on ferme ?

**Comment by RobinPetit** [comment]
Folks ? :p

**Comment by detobel36** [comment]
On verra à la limite pour la partie rapport :stuck_out_tongue:
