### ISSUE TITLE
[Prototype] Utilité des fichiers XMLMap/Example{2}.xml ?

### ISSUE THREAD

**Issue by RobinPetit** [RobinPetit/OpenWifiLocalizator#19]
On peut voir, dans la branche `prototype´ qu'il y a deux fichiers d'exemples : https://github.com/RobinPetit/OpenWifiLocalizator/blob/prototype/OWL/app/src/main/assets/XMLMap/ExampleXML2.xml et https://github.com/RobinPetit/OpenWifiLocalizator/blob/prototype/OWL/app/src/main/assets/XMLMap/ExampleXML.xml et j'aimerais bien savoir à quoi ils servent. S'ils ne servent à rien, buiten, merci d'être venu ! :D

**Comment by detobel36** [comment]
Ils ont servit...  Paix à leur âmes... :skull:           
On peut delete :stuck_out_tongue:

**Comment by RobinPetit** [comment]
Ça, c'est fait.
