### ISSUE TITLE
Besoins de l'appli de création du graphe

### ISSUE THREAD

**Issue by RobinPetit** [RobinPetit/OpenWifiLocalizator#2]
Comme discuté dans #1, il y a une application (à priori Python3/Tkinter pour la simplicité) à réaliser pour que l'on puisse réaliser les sous-graphes de bâtiments (et donc le graphe général). Précisément, de quoi cette application a-t-elle besoin ?

- [x] créer des nœuds ;
- [x] les nommer ;
- [x] les relier (en faisant attention aux doublons) ;
- [x] afficher une image en background pour placer les nœuds ;
- [x] mémoriser où se trouvent les nœuds sur la carte ;
- [x] retirer des nœuds, arêtes ;
- [x] mettre un poids aux arêtes ;
- [x] éditer les nœuds et arêtes ;
- [x] zoomer/dézoomer sur la carte **--> avorté** ;
- [x] se déplacer vers le haut/bas/gauche/droite ;
- [x] gérer des alias pour les nœuds ;
- [x] recharger un XML pour poursuivre la création/éditer.

Êtes-vous d'accord ? Y a-t-il des points à changer/ajouter/supprimer ?

**EDIT:** je complète au fur et à mesure en cochant ce qui est fait.

**Comment by NathanLiccardo** [comment]
Je pense être (comme Remy) un peux perdu par rapport à l'utilité de ce programme ... 
Donc l'idée c'est de créer un script Python qui permet de deja avoir une interface et de positionner l'utilisateur ? (Si j'ai bien compris) pourquoi ne pas directement réaliser le projet final avec les cartes et la localisation ?

**Comment by RobinPetit** [comment]
L'idée est d'avoir un script qui nous permette de placer les nœuds du graphe chacun de notre côté, afin d'avoir une manière identique de stocker les données. Donc pas besoin de localiser ou positionner l'utilisateur. Juste cliquer pour faire des nœuds quand on a les plans sous les yeux pour créer le graphe d'un bâtiment.

**Comment by RobinPetit** [comment]
Le but c'est donc d'avoir quelque chose qui se code vite pour qu'on puisse vite s'y mettre une fois qu'on a les plans.

**Comment by RobinPetit** [comment]
:+1:

**Comment by NathanLiccardo** [comment]
OK ! J'ai compris :D

**Comment by RobinPetit** [comment]
Bon voilà, l'app est presque terminée, il faut encore sauver l'état du graphe et gérer les zooms/dezoom (qui vont être un brin lourd je pense).

**Comment by RobinPetit** [comment]
Le commit 55b9f30 donne un exemple de fichier XML. Vous pouvez y jjeter un oeil afin d'être sûrs qu'on est sur la même longueur d'onde tant pour le XML *raw* que pour le graphe qui est dedans ?

**Comment by denishoornaert** [comment]
>Pour moi c'est bon. Cependant avec remy on se demandait si il n'était pas plus intérressant de ne pas mettre de tabulation dans nos xml de manière a rendre les fichiers moins volumineux... On se disait que puisqu'on ne manipulera les xml que par le programme python, la lisibilté du xml n'est plus si importante.
Qu'en penses tu ?

**Comment by RobinPetit** [comment]
Je ne suis pas sûr que ça changera grand chose, mais c'est juste un argument à changer au final, c'est pas compliqué.

**Comment by detobel36** [comment]
> Le commit 55b9f30 donne un exemple de fichier XML.             

Bah heu... On avait déjà fait un modèle :stuck_out_tongue:  
:arrow_right: https://github.com/RobinPetit/OpenWifiLocalizator/blob/prototype/prototype/src/ExampleXML.xml          
Je pense qu'il y a moyen de faire un mixe des deux :smiley:

**Comment by RobinPetit** [comment]
Oui, c'est sur celui-là que je me suis basé pour le format XML. Je le mets dans le commit pour montrer ce que donne la génération du programme. ;)

**Comment by RobinPetit** [comment]
La branche a été *mergée* sur master, du coup, on ferme ici ?

**Comment by detobel36** [comment]
Y a juste que @Denis à merge prototype avec GraphMaker et un peu Master...      
Va voir dans `graph` > `netwok` :stuck_out_tongue:

**Comment by RobinPetit** [comment]
Je sens que Denis fait déjà n'importe quoi ! Paas bien !

**Comment by RobinPetit** [comment]
Bon du coup, je ferme cette issue. En cas de problème sur le script GraphMaker, on réouvrira une issue.
