### ISSUE TITLE
[Prototype] Tâche au niveau Graphique

### ISSUE THREAD

**Issue by detobel36** [RobinPetit/OpenWifiLocalizator#20]
Voici ce qu'il nous reste à faire au niveau graphique:

- [x]  relancer un scan toutes les x sec/min pour être sur qu'on a pas bougé ;
- [x]  ajouter un bouton pour relancer manuellement le scan ;
- [x]  afficher le plus court chemin sur le plan ;
- [x]  modifier le plus court chemin (où en tout cas l'affichage) une fois qu'on avance (voir premier point) ;
- [ ]  permettre de changer de plan ?  (pour pouvoir voir le trajet que va nous faire faire l'app en avance 😉 ).

**Comment by RobinPetit** [comment]
Je viens de me poser une question : 

### Mise en situation

un utilisateur lance l'app, trouve le + court chemin entre les nœuds S (source) et D (destination). L'app scanne toutes les x secondes pour vérifier que l'utilisateur suit le bon chemin.

### Souci

Lors du nème scan, l'app détecte que l'utilisateur n'est sur aucun nœud du chemin.  Pour recalculer le chemin, on recalcule entre le nœud C (le nœud où est l'utilisateur) et le nœud D ou juste entre le nœud C et le nœud I (intérieur au chemin), qui est le premier nœud du chemin (ordonné) que l'utilisateur n'a pas visité (et donc le nœud avant lequel il a bifurqué) ?

**Comment by detobel36** [comment]
Pour moi faut recalculer avec D.     
A la limite y a peut-être moyen d'optimiser en faisant d'abord le test avec I :wink:

**Comment by denishoornaert** [comment]
J'ai déjà implémenté un système pour déssiner un chemin. Celui-ci se trouve dans la classe DrawView (qui n'est pas encore implémenté pour diverses raisons...) le nom de la méthode est Draw et prend un objet path en paramètre. Il me suffira donc d'overloader le méthode pour que celle-ci prenne aussi en charge un ArrayList de Path.

**Comment by RobinPetit** [comment]
Par rapport à la question de vers quel point il faut rediriger en cas de non-suivi du chemin indiqué", mon père a eu raison en me disant que si l'utilisateur n'est pas sur le chemin, c'est probablement qu'il y a un souci pour y arriver et donc c'est pas une bonne idée de recalculer pour aller vers là. Ça me semble assez logique... Du coup recalcul vers la destination... !

**Comment by RobinPetit** [comment]
Du coup, on ferme ici...
