### ISSUE TITLE
Vérifier que les logs fonctionne bien

### ISSUE THREAD

**Issue by detobel36** [RobinPetit/OpenWifiLocalizator#21]
J'ai remarqué que mon téléphone n'enregistrait plus correctement les logs :disappointed_relieved:

**Comment by RobinPetit** [comment]
Ils sont censés s'enregistrer où les logs ?

**Comment by detobel36** [comment]
A la racine de ton GSM dans `/OWL/log/<timestramp>_cat.txt`

**Comment by detobel36** [comment]
C'est simplement le `DEBUG` qui doit être à true pour permettre d'avoir toutes les logs sur le GSM.           
Je peux changer ça au besoin mais je trouvais que ça spammais moi :wink:

**Comment by RobinPetit** [comment]
Tant qu'on le sait, c'est bon. ;)
