### ISSUE TITLE
Bug au format paysage

### ISSUE THREAD

**Issue by RobinPetit** [RobinPetit/OpenWifiLocalizator#23]
Quand on met le phone à l'horizontale et qu'on essaye de déplacer l'image, elle ne bouge pas, et seul le point de localisation se déplace... Je ne sais pas qui saurait régler ça ( @NathanLiccardo ? ) et je ne pense pas que ce soit urgent non plus.

**Comment by NathanLiccardo** [comment]
5e74cab : (devrait) régler le problème.

Bon scan !

Amicalement votre, 
La star

**Comment by detobel36** [comment]
ça fonctionne :smile:               
Je close
