### ISSUE TITLE
Points a compléter pour le printemps des sciences

### ISSUE THREAD

**Issue by denishoornaert** [RobinPetit/OpenWifiLocalizator#25]
Si vous voyez quoique ce soit de plus, n'hésitez pas à le dire.
<h3>Général</h3>

- [x] Réunion (pour plan de travail, ...)
- [x] Roadmap/planning
- [x] Faire une release ??
- [x] Structurer le git (Existence de "prototype" ??)
- [x] Lieu de stockage pour données communes ne pouvant pas se retrouver sur le repo git.

<h3>Distribution de l'application</h3> @NathanLiccardo

- [x] autorisation de l'ulb (à qui demander ?)
- [ ] QR code (statique, ...)
- [x] Logo OWL accepté

<h3>Plan</h3>

- [x] Exemple convention @denishoornaert
- [x] Gestion de la distance entre deux plans
- [x] Création des plans (images) schématisés (utilisation de *inkscape*+*The gimp*)
- [X] Poser des conventions sur la modélisation (points de repère, points non scannés, ...)
- [x] Modélisation des plans (placement des points)
- [x] Scan pour chaque point
- [x] Passage de XML à SQL @denishoornaert / @detobel36 / @RobinPetit (c.f. #36)

<h3>Localisation</h3>

- [x] Améliorer ou changer l'algorithme de localisation @denishoornaert
- [x] Refresh tout les x temps sur l'application @detobel36 

<h3>Application affichage</h3> @NathanLiccardo 

- [ ] Changement de plan
- [ ] Reset du calque lors d'un changement de plan ou de chemin/direction
- [x] Implémentation de splines pour le dessin d'une trajectoire (@RobinPetit)

<h3>GraphMaker</h3> @RobinPetit 

- [x] Possibilité de bouger les points (Pour éviter les chemeins collés aux murs)

<h3>Langues</h3> @detobel36 @RobinPetit @NathanLiccardo
- [x] déterminer les langues (choix: fr, en, nl, de).

<h3>Rapport/État de l'art</h3> @detobel36 @RobinPetit @NathanLiccardo

- [ ] Demander consignes précises (nombre de pages, ...)
- [x] Discuter place des partie proche de l'impléméntation et non directement lié à l'état de l'art
- [x] UML
- [ ] Explication des algorithmes utilsés et des alternatives
- [ ] Bibliographie

<h3>Outils "pédagogiques" pour la présentation</h3>

- [ ] Création d'un site web sur le quel on peut mettre nos sources, nos images/animations utilisé pour la présentation et où on pourra renvoyer les gens pour avoir plus d'explication. et aussi faire pub si un jours on distribut.

<h3>Easter eggs</h3>

- [ ] Where is Charlie (ou Brian)
- [ ] OuEtDoncOrNiCar

**Comment by RobinPetit** [comment]
Idem, vu qu'on y est au pds, on fait quoi de l'issue ? On recrée des issues pour les éléments postposés ?

**Comment by detobel36** [comment]
Ouep, on peut close et au pire on rouvrira des issues pour une tâche précise

**Comment by RobinPetit** [comment]
Ok du coup je ferme
