### ISSUE TITLE
Conversion XML en SQL

### ISSUE THREAD

**Issue by detobel36** [RobinPetit/OpenWifiLocalizator#27]
L'idée est d'utiliser du SQLitle à la place du XML.

- [ ] Relation-Entité
- [x] Conversion des fichiers XML en SQL
- [x] Adaptation du GraphMaker (@RobinPetit)
    - [x] Sauvegarde
    - [x] Chargement
    - [x] Vérifications
- [x] Adaptation du code Java `Android`

**Comment by detobel36** [comment]
Voir #12 (si toujours d'actualité)

**Comment by RobinPetit** [comment]
On va laisser tomber les XMLs donc voilà. :cactus:

**Comment by detobel36** [comment]
*Relation-Entité* :arrow_right: https://github.com/RobinPetit/OpenWifiLocalizator/blob/sql/report/images/entity-relation.jpg        
Doit être mis à jour ( @denishoornaert )
           
-------------
Les fichiers XML ne seront pas réutilisé (recommence à zéro)

**Comment by RobinPetit** [comment]
Pour la relation entité, on en est où ?
