### ISSUE TITLE
Ajouter licence Header

### ISSUE THREAD

**Issue by detobel36** [RobinPetit/OpenWifiLocalizator#3]
Il faut produire une licence pour le projet Java         
@RobinPetit ? :stuck_out_tongue:

**Comment by RobinPetit** [comment]
Une licence ?

**Comment by detobel36** [comment]
Bah une licence :stuck_out_tongue:                      
https://zestedesavoir.com/tutoriels/261/le-droit-dauteur-creative-commons-et-les-licences-sur-zeste-de-savoir/

**Comment by RobinPetit** [comment]
Bah pour du code, je dirais GPL ou MIT, t'en penses quoi ?

**Comment by RobinPetit** [comment]
Bon, du coup ? ;)

**Comment by RobinPetit** [comment]
Du coup, on s'est mis d'accord sur une GPL (v3).
