### ISSUE TITLE
Créer un objet Campus

### ISSUE THREAD

**Issue by detobel36** [RobinPetit/OpenWifiLocalizator#34]
Lors de la création de la base de donnée, nous nous sommes rendu compte que les plans généraux n'ont pas vraiment les même fonction qu'un bête plan représentant un batiment.        
En fait le problème vient du fait que nous avons fixé manuellement le nom des campus.        
             
Chaque plan a des coordonnées sur son "plan parent" (un campus donc).   Comment représenter ça en base de données ?        
Nous avons une table Campus qui contient un id et un nom.  Les plans font donc une référence vers cette table.               
           
**Concrètement:** réfléchir sur l'utilité d'avoir une class Campus et comment représenter les plans des campus

**Comment by RobinPetit** [comment]
Je suis tout à fait d'accord, ça m'avait même un peu emêté quand j'ai ajouté des infos sur les plans de bâtiments parce que j'avais des champs pas tout le temps utilisé et c'est pas bien. Donc du coup, il faudrait une structure propre du genre une classe abstraite `Plan`, puis deux classes qui en héritent : `CampusPlan` et `BuildingPlan` ou un truc du genre.

**Comment by detobel36** [comment]
Première implémentation ici 28497ef8bc1f357ef44d9b61c5dfc75c70d95d36        
Suite dans le commit ci-dessus.
