### ISSUE TITLE
[BDD] Champs superflus.

### ISSUE THREAD

**Issue by denishoornaert** [RobinPetit/OpenWifiLocalizator#39]
Liste des champs qui ne devraient pas exister.
(Pour sauver votre champ favori, envoyez Champ au 3434. (1£/SMS) )

- [x] `Wifi.Min`
- [x] `Wifi.Max`
- [x] `Building.ImagePath` (gardé)
- [x] `Alias.NodeId`
- [x] `Edge.Weight` (voir #40)

**Comment by RobinPetit** [comment]
Que de tromperies ! j'ai envoyé Champ-Alias.NodeId et il est quand même plus là ! :angry:

**Comment by denishoornaert** [comment]
Pour ImagePath, si on ne le garde pas, alors on ne saura pas si l'image se trouve dans un dossier (ex: S_U/S_UA_1_FOND DE PLAN.png). La solution serait donc de tout mettre à la "racine".

**Comment by detobel36** [comment]
On peut au moins le split en 2 dossiers: un par campus

**Comment by RobinPetit** [comment]
Ouais c'est ce que j'avais en tête :)

**Comment by denishoornaert** [comment]
ok on peut faire ça ^^. Après est ce que ca un interret de séparer les fichiers en seulement deux dossiers ? :/

**Comment by RobinPetit** [comment]
Oui, j'avais ça en tête au caus où on a des bâtiments qui ont le même nom entre Plaine et Solbosch, mais vu qu'on a le `P_` ou le `S_` devant, on s'en balek. :cactus:

**Comment by RobinPetit** [comment]
Du ocup, on prend quelle solution pour `Building.ImagePath` ?

**Comment by detobel36** [comment]
`Building.ImagePath`              
**Avantages:**
- Peut trier les images et ne pas toutes les avoir dans un dossier                  

**Défaut:**
- Il faut renseigner cette information dans la base de donnée (ça prend de la place)


Editer mon message si vous voyez d'autres choses
