### ISSUE TITLE
Voir comment utiliser les méthodes `default` des interfaces sur les enum des tables SQL dans OWL

### ISSUE THREAD

**Issue by RobinPetit** [RobinPetit/OpenWifiLocalizator#43]
Actuellement, il y a des méthodes qui sont strictement identiques dans toutes les `enum` qui représentent une table de la DB dans `OWL`. Java8 permet de définir des méthodes `default` dans les interfaces (c.f. https://docs.oracle.com/javase/tutorial/java/IandI/defaultmethods.html), donc il faudrait voir s'il est possible d'utiliser cela dans OWL ou si on ne peut pas utiliser les features Java8 (c.f. https://developer.android.com/guide/platform/j8-jack.html).

**Comment by detobel36** [comment]
Fix in 3841415b5784a44d866c21c231c6ccbaebcd55af
