### ISSUE TITLE
Faire le power point

### ISSUE THREAD

**Issue by detobel36** [RobinPetit/OpenWifiLocalizator#48]
Il faut faire un power point pour expliquer le projet au printemps des sciences.
              
- [x] Introduction et remise dans le contexte
 
- [x] Introduction (logo, nom, but, ...)
- [x] Qu'est-ce qu'un wifi (gif avec le wifi qui bouge (cfr robin))
- [x] Un point capte plusieurs wifi
- [x] Mesure ces wifi
- [x] Plan où on prend ces wifi (déplacement des wifi sur la droite de l'image). 
    *Concrètement:* Le bonhomme fait un scan, le point passe au vert, les scans vont se mettre à droite, le bonhomme se déplace au point suivant, ect pour 2-3 points.
- [x] On montre le plan avec tous les points fait
- [x] Un utilisateur cherche sa position (avec un point d'interrogation, qqch comme ça), il capte des wifis.  Et les wifi capté match exactement avec ceux du slide précédent (! on conserve leur place (plus simple pour la transposition))
- [x] On montre l'application (une recherche et le résultat de celle-ci)
- [x] Ajout de la partie localisation
- [x] Ajout de GraphMaker à la fin de la préso "lambda"
- [x] Ajout d'une conclusion de l'avancée du travail
- [x] Ajout d'une démo live

### Images

- https://owncloud.ulb.ac.be/index.php/s/39RnFh1xeJLz0hF

![whatsapp image 2017-02-07 at 13 01 18](https://cloud.githubusercontent.com/assets/5373615/22740569/a3ca3570-ee10-11e6-885e-1d2767b6590a.jpeg)

**Comment by detobel36** [comment]
Répartition du PowerPoint:             
- **Nathan**
1 à 6
- **Robin**
7 à 10
- **Rémy**
11 (démo)
- **Denis**
12 à 18
- **Rémy**
19 à 21
       
---------------------------
Ajouter un slide avec un plot 3D Wifi

             
--------------------------
Correction à faire:           
- **Slide 6**: A petit et loin, B grand et proche, C moyen
- **Slide 7**: Bug affichage ("recherche" pas affiché trop longtemps)
- **Slide 20**: "BigData"
- **Slide 21**: Enrichir

**Comment by detobel36** [comment]
Voici la nouvelle version (normalement les bugs ci-dessus ont été corrigés)
[Open Wifi Localizator.pptx](https://github.com/RobinPetit/OpenWifiLocalizator/files/801822/Open.Wifi.Localizator.pptx)

**Comment by RobinPetit** [comment]
On ferme ça ici ?

**Comment by RobinPetit** [comment]
Je ferme également : le ppt est fait.
