### ISSUE TITLE
Refaire le logo

### ISSUE THREAD

**Issue by detobel36** [RobinPetit/OpenWifiLocalizator#49]
Voir #28            
L'idée était donc d'avoir un logo rond avec le texte légèrement décalé, une couleur moins "bleu" type "ULB" et changer légèrement la police.         

--------------

Logo refusé par l'ULB: ![logo owl](https://cloud.githubusercontent.com/assets/5373615/22624890/f0116302-eb88-11e6-9273-884fb304c76b.png)

**Comment by NathanLiccardo** [comment]
Qu'est-ce que vous voulez dire par "légèrement" décalé ?

**Comment by detobel36** [comment]
Le bon mot aurait été penché.      
Par exemple de 20-30 degré pour ne pas avoir un texte à l'horizontale :smiley:

**Comment by NathanLiccardo** [comment]
Ok alors je vais le faire comme ça on peut l'intégrer aux slides aussi ;) La police on peut changer complètement aussi ? :)

**Comment by NathanLiccardo** [comment]
Première idée : 
![logo1](https://cloud.githubusercontent.com/assets/16730992/22775413/f2a39e48-eeab-11e6-8e8f-b0a9232f7819.png)

**Comment by detobel36** [comment]
Wow...          
J'avais pas du tout ça en tête...            
Moi je voyais plus une couleur bleu entre celle de l'ULB et le mauve représentatif de la fac des sciences.
Pour le texte je voyais pas à l'horizontal mais juste légèrement décalé.  Assez pour le voir mais pas excessif.  Et les lettres j'aurais retiré le coins replié du L (qui est typique ULB) mais gardé la grosseur du trait (à la limite supprimé les débordements t qui "font" la police, et du coup avoir qqch de plus flat).
         
Après je dis pas que c'est pas bien, c'est juste que c'est pas ça que j'imaginais...

**Comment by NathanLiccardo** [comment]
tkt je comprends :) j'en fait 2-3 puis on peut choisir ;) je vais essayer de faire ce que tu proposes mais je promet rien :p 

![logo2](https://cloud.githubusercontent.com/assets/16730992/22776017/5d006062-eeae-11e6-8d67-d130e2aebdc9.png)

**Comment by NathanLiccardo** [comment]
Et le dernier (perso c'est celui que je préfère) j'ai essayer de m'inspirer de ce que tu avais dit rémy mais les couleurs mauves et bleue sont super agressives alors c'est tendu de faire un joli truc avec :/ 

![logo3](https://cloud.githubusercontent.com/assets/16730992/22776412/d67c55da-eeaf-11e6-9c2a-812b95670c0d.png)

**Comment by detobel36** [comment]
Moi je pensais vraiment plus à qqch comme ça:
![res](https://cloud.githubusercontent.com/assets/5373615/22776679/e296905a-eeb0-11e6-9311-1a1f95796de8.png)

**Comment by NathanLiccardo** [comment]
ok mais quel est la police ? Je sais pas trop perso je préfère le dernier que j'ai post .. Pcq ce que tu as fait avec les lettres c'est pas terrible :/

**Comment by detobel36** [comment]
C'est la police ULB - les bords...  J'ai retouché à la main.  C'est une police qui existe pas.          
Bien sur mon image est pixelisé, j'ai fait ça vite fait en paint...
Concrètement en rond ça donne ça: 
![res](https://cloud.githubusercontent.com/assets/5373615/22776857/92132322-eeb1-11e6-9259-92835153abe0.png)       
Après la qualité et pas top...  Mais c'est parce que c'est vite fait :stuck_out_tongue:

**Comment by denishoornaert** [comment]
@NathanLiccardo J'aime bien ton dernier. Par contre niveau couleur je suis d'accord avec @detobel36 même si je comprend bien que cela fasse flashy avec celles proposées. Néanmoins, je pense que si les lettres étaient blanche cela passerait surement mieux :) En ce qui concerne la police, j'aime bien mais est ce que elle ne serait pas un peut trop grande ? on voit que le "O" est de travers :/

PS: Le premier logo m'a fait penser à : 
![](http://www.ateliermagique.com/uploads/thumbnails/uploads/drawing/005700/005601/le-cri-de-munch_500x500.jpg)

**Comment by NathanLiccardo** [comment]
Step by step : 

- je veux bien reprendre un mauve et vous le montrer mais je trouve que ce sera pas très joli mais ok ok je vais le faire :p 

- Pour la taille de la police je peux faire plus petit mais faut penser que c'est une icône donc elle sera petite. Si les lettres sont grandes mnt, elles seront "normales" après ;)

- pour le "o" c'était fait exprès c'est pour donner un peux de mouvement moi j'aimais bien ^^

**Comment by denishoornaert** [comment]
Pour la police je veux bien qu'elle doit être grande mais je te domande pas de la mettre en 10 :p juste qu'on ait pas l'impression que le "O" et le "L" essaye de se faire la malle :p

**Comment by denishoornaert** [comment]
Pour le mouvement : je préferait alors que toute les lettres soient en italique :) (mon point de vu :p )

**Comment by NathanLiccardo** [comment]
![logo4](https://cloud.githubusercontent.com/assets/16730992/22778864/be9c09c0-eeb8-11e6-867b-d54ef8a1b18b.png)

Ok ?

**Comment by denishoornaert** [comment]
Moi j'aime bien :D 
Après je vois se qui te préoccupe avec la couleur :/
J'aime le modèle mais faudra voir ce que @RobinPetit en dit. Si il valide alors on rentrera dans les détails et chipotant légèrement a la couleur de manière a arriver à un concensus :)
Mais toi qu'en penses tu ? :)

**Comment by NathanLiccardo** [comment]
Non pour moi le dernier c'est bon ;)

**Comment by denishoornaert** [comment]
Vous êtes pas chaud de remonter le "OWL" et de mettre en dessous en petit un truc du genre ?
![](https://cdn3.iconfinder.com/data/icons/glypho-travel/64/map-pin-marker-512.png)

**Comment by detobel36** [comment]
@denishoornaert ou alors on utilise ça pour faire le O :stuck_out_tongue:          
Ca change pas mal l'idée de base et je sais pas ce que ça peut rendre :confused:

**Comment by NathanLiccardo** [comment]
![logo5](https://cloud.githubusercontent.com/assets/16730992/22779867/c8bf0b1a-eebc-11e6-9a15-bb2870dd4958.png)

**Comment by denishoornaert** [comment]
Je suis d'accord cependant je me disais que au moins cela ferait comprendre qu'il s'agit d'un systeme de ocalisation :)
PS: La rapidité du @NathanLiccardo  ^^

**Comment by denishoornaert** [comment]
Ca charge pas trop le logo :/ ?

**Comment by NathanLiccardo** [comment]
![logo6](https://cloud.githubusercontent.com/assets/16730992/22780050/7e2a608a-eebd-11e6-8788-f641abc9f3b4.png)

**Comment by denishoornaert** [comment]
Je suis pas super fan du dernier model :/ Mais on sera fixé une fois que @RobinPetit sera revenu à la vie ^^

**Comment by NathanLiccardo** [comment]
Voila le final ;) par contre je n'arrive pas à faire du relief mais je trouve qu'il donne bien comme ça ;) 

![logo5](https://cloud.githubusercontent.com/assets/16730992/22831398/8407239c-efaa-11e6-9a4c-297aef2628dc.png)

**Comment by RobinPetit** [comment]
Hey folks!

> Toujours vivant, rassurez-vous
> Toujours la patate, toujours debout !

Pour le logo, je trouve le dernier vraiment pas mal en terme de consensus de couleur.

Je propose ceci comme changements :
+ mettre *OWL* en italique ;
+ Faire un empattement du « L » rappelant celui de l'ULB (donc je dirais modifier le bout de la lettre à la main) ;
+ essayer de mettre une sorte d'anti-aliasing sur le contour du disque, afin de *polir* le contour ;
+ pareil pour le logo de localisation qui a l'air de s'être pixelisé au passage black->white.

En tout cas, je trouve que ça donne vachement bien. Faudrait voir ce que donne ce cercle sur un carré du bleu de l'ULB afin de voir si la couleur colle vraiment bien. :)

**Comment by NathanLiccardo** [comment]
![logo5](https://cloud.githubusercontent.com/assets/16730992/23066453/f91cfbb4-f51a-11e6-98f5-9947fd91110d.png)

**Comment by NathanLiccardo** [comment]
C'est finiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii 🌵

**Comment by detobel36** [comment]
Police utilisée: `Nimbus Mono L Bold`
