### ISSUE TITLE
Suppression de la branche prototype

### ISSUE THREAD

**Issue by RobinPetit** [RobinPetit/OpenWifiLocalizator#5]
Est-ce que tout le contenu de `prototype` est bien dans `prototype_fix` ? Si oui, peut-on supprimer `prototype` et renommer `prototype_fix` en `prototype` ?

**Comment by detobel36** [comment]
Je pense que l'on peut oui :smile:

**Comment by detobel36** [comment]
Je confirme, depuis 10 jours on a pas eu besoin de la branche "cassée" :wink:

**Comment by RobinPetit** [comment]
Du coup, on n'a plus la branche `prototype`. Je te laise créer la nouvelle branche `prototype` ? Je dis ça puisque c'est surtout toi qui codes desus donc il te suffit de te mettre sur `prototype_fix`, de faire une nouvelle branche en partant de celle-là et de l'appeler `prototype` et de faire un beau petit push. Après ça, il restera plus qu'à retirer l'actuelle `prototype_fix` du dépôt. Ça te va ?

**Comment by detobel36** [comment]
Normalement tu peux renommer une branche...
Mais tkt je peux faire ça à l'occasion :)

**Comment by detobel36** [comment]
Après moulte rebondissement, j'ai enfin réussi à merge ! :laughing:

**Comment by RobinPetit** [comment]
Nom d'une pipe en bois, sagouin ! Il a mis un *e* à *moult* !

Sinon, cool ! :leopard:

**Comment by RobinPetit** [comment]
Du coup je ferme. ;)

**Comment by RobinPetit** [comment]
Je vois que tu n'as pas supprimé `prototype_fix`, c'est volontaire ou on peut virer ?

**Comment by detobel36** [comment]
Je voulais être sur qu'on allait pas perdre les commits...              
J'attendais ta confirmation xD
            
YOLO, tu peux delete :stuck_out_tongue_winking_eye:

**Comment by RobinPetit** [comment]
Done. ;)
