### ISSUE TITLE
Warning SQLite

### ISSUE THREAD

**Issue by detobel36** [RobinPetit/OpenWifiLocalizator#53]
`E/SQLiteLog: (284) automatic index on Wifi(BSS)`           
Pour corrigé ceci il faut rajouter un index sur les BSS des wifi (ce qu'on fait assez souvent en table).          
Il faut également vérifier qu'il y a bien un index et un unique sur la colonne "ID" de toutes les tables :smiley:

**Comment by detobel36** [comment]
@denishoornaert il faudra juste mettre à jour les bdd owncloud :smile:

**Comment by denishoornaert** [comment]
nah je veux pas :p Ok ok je vais le faire :p
