### ISSUE TITLE
Création de lien entre différent plan

### ISSUE THREAD

**Issue by detobel36** [RobinPetit/OpenWifiLocalizator#6]
Comment fait-on pour relier deux plans au niveau XML ?          
Actuellement dans l'XML on peut trouver ce genre de ligne:             
```
<edge beg="B.1.307" end="B.1.HALL.3" weight="4.02" />
```              
Mais cela ne relie que deux points présent sur un même graphe.   Pour relier deux graphes, il me semble logique d'utiliser également des "edge"/"path".  Bref, il y a deux problèmes:

1. Où stocker les chemins reliant deux graphes ?  En double dans les deux XML, dans un XML à part ? :disappointed_relieved: 
2. Comment créer un chemin (`edge`/`path`) alors que les `Nodes` ne sont pas créé ?  Sauf si on décide de charger tous les `Nodes` en mémoire et **ensuite** tous les chemins.

**Comment by RobinPetit** [comment]
Bon finalement j'ai pas répondu, je me susi un peu perdu...
Finalement, on a décidé de faire les XMLs sous la forme suivante, c'est bien ça ?

```
<plan>
	<nodes>
		<node>
		</node>
		...
	</nodes>
	<edges>
		<internal>
			<edge>
			</edge>
			...
		</internal>
		<external>
			<edge>
			</edge>
			...
		</external>
	</edges>
</plan>
```

**Comment by detobel36** [comment]
J'ai modifié le fichier d'exemple dans le prototype (cfr: https://github.com/RobinPetit/OpenWifiLocalizator/commit/73b8512b1bda65678001bcbf4e4fa90af7d0bc85 )
Il reste encore à faire l'implémentation dans le dit prototype mais également dans le `GraphMaker`

**Comment by detobel36** [comment]
J'ai commencé la modification sur le GraphMaker ici: https://github.com/RobinPetit/OpenWifiLocalizator/commit/7c0d2a87749b7b7b973f798b3880df79f3ef3f22        

- [x] Adapter le fichier sauvegardé
- [ ] Adapter le parser

**Comment by RobinPetit** [comment]
Je me suis lancé sur la mise à jour du XML côté Py.

**Comment by detobel36** [comment]
C'est déjà fait pour les liens internes et les points...
https://github.com/RobinPetit/OpenWifiLocalizator/commit/7c0d2a87749b7b7b973f798b3880df79f3ef3f22

**Comment by RobinPetit** [comment]
Yep, ça j'ai déjà vu, ça fait un moment. ;) Je me suis attaqué à la suite du parser.

**Comment by RobinPetit** [comment]
Voilà, actuellement il y a des liens externes qui sont créés et enregistrés. Le seul truc c'est qu'ils ne sont enregistrés que d'un seul côté (dans un seul XML). Il fauat donc encore gérer l'ajout dans l'autre XML.

Et sinon faudra faire gaffe aux changement de noms de nœuds étant reliés à des nœuds extérieurs car il faudrait implémenter ça aussi...

**Comment by RobinPetit** [comment]
Ah et également, il faudra pouvoir mettre une longueur à ces arêtes extérieures...

**Comment by detobel36** [comment]
[Prototype] Il peut charger les liens externes :smiley:  https://github.com/RobinPetit/OpenWifiLocalizator/commit/5f951b4e11b2fb3f6c3f6ae74e95ad6cb80a88a0             
Cependant il ne prend pas encore en compte les 2 premières lignes (à savoir  `background_image` et `distance_unit`)

**Comment by RobinPetit** [comment]
Bah `background_image` ne devrait plus exister vu que le nom esst le même que le XML et `distance_unit` ne devrait pas servir à l'app Java, mais uniquement au GraphMaker, non ?
