### ISSUE TITLE
Panneau

### ISSUE THREAD

**Issue by detobel36** [RobinPetit/OpenWifiLocalizator#60]
## Liste des tâches
- Image pour le header du poster.           
    Image de 19,47 cm par 87,77 cm
- Poster abordable
- Poster scientifique

### Panneau abordable/didactique
- Pourquoi l'application (utilité, but, ect).
- Explication des wifis.
- Utilité de GraphMaker
- Explication des graphes

### Panneau sérieux
- Trilateration 
- Variance 
- Spline

**Comment by detobel36** [comment]
## Infos
http://sciences.ulb.ac.be/printemps/expo-exposants/

> Les posters doivent donc être concis, avec des messages bien structurés sur 3 niveaux :
> - la présentation du problème posé, 
> - la description du projet, de l’expérience réalisée,
> - les conclusions.

**Comment by detobel36** [comment]
Je dois encore mettre les images dans les PowerPoints...  Et j'ai besoin de @RobinPetit et @denishoornaert pour la partie plus "théorique" histoire de pas dire de la merde xD                

- Partie 1 [ulb_sciences_2017-Partie2.pptx](https://github.com/RobinPetit/OpenWifiLocalizator/files/799940/ulb_sciences_2017-Partie2.pptx)
- Partie 2 [ulb_sciences_2017-Partie1.pptx](https://github.com/RobinPetit/OpenWifiLocalizator/files/799941/ulb_sciences_2017-Partie1.pptx)


C'est une première version.  Evidemment on modifiera pour rendre ça plus simple, plus illustré, ...  Mais au moins on a déjà une base 😄

**Comment by denishoornaert** [comment]
De manière générale : 

- Il faudrait remplacer les "nous" par des "on" ou du discours indirecte (plus formel, et etc.).
- Il faudra penser à mettre plus de shémas.
- Le texte ne sera t-il pas trop prédominant ? (taille de police, ...)

Partie "Fonctionnemnt" indiqué que l'avantage est d'avoir une notion de tridimension (étages, ...)
Partie "A*" : J'ai rien compris :p

**Comment by detobel36** [comment]
Répartition de la *V2* des panneaux: 

### Simple             
- **Introduction**: @NathanLiccardo 
- **Qualité des wifis:** @denishoornaert 
- **Modélisation**: @detobel36


### Avancé
- **Plus cours chemin**: @RobinPetit  & @denishoornaert 
- **Spline**: (simple schéma) @RobinPetit

**Comment by RobinPetit** [comment]
Les panneaux sont faits du coup je supprime.
