### ISSUE TITLE
Prototype

### ISSUE THREAD

**Issue by denishoornaert** [RobinPetit/OpenWifiLocalizator#7]
Liste des points à aborder pour finir le prototype (deadline le 19 septembre).
- [x] Dijkstra (@RobinPetit);
- [x] Recherche du nœud matchant les wifi détectés (@denishoornaert );
- [x] Gestion du cas des collisions entre nœuds (@denishoornaert );
- [x] Modélisation du OF & extérieurs (@denishoornaert );
- [x] Ajout d'un système de log (@Detobel36) .

Indiquez ci-dessous tout les points supplémentaires à traiter de manière à ce que je puisse les ajouter à la liste ;)

**Comment by RobinPetit** [comment]
Ok super, je propose qu'on mette également en gras entre parenthèses les assignés à une certaine tâche, on voit plus facilement qui fait quoi et ce qui n'est traité par personne. :)

**Comment by detobel36** [comment]
:white_check_mark: système de log :smiley:

**Comment by RobinPetit** [comment]
Pour Dijkstra (enfin plutôt A*), j'ai créé une nouvelle branche (sobrement intitulée Astar) pour que l'avancement ne soit pas dérangé et ne dérange pas le reste du prototype.

**Comment by RobinPetit** [comment]
Bon du coup ici tout est fait. Que reste-t-il à faire ? @denishoornaert tu peux mettre à jour le post original ?

**Comment by detobel36** [comment]
Il reste à faire des fonctionnalités "graphique".  Je pense que ce serait plus simple de refaire une issue et de clôturer celle-ci :smile:

**Comment by RobinPetit** [comment]
Deal ! :cactus:
